In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [4]:
# File to Load
comic_path = 'Resources/books_clean.csv'

# Read the modified Comic Books csv and store into Pandas DataFrame
comic_df = pd.read_csv(comic_path)
comic_df

,ISBN,Title,Other Titles,Author,All Names,Country of Publication,Place of Publication,Publisher,Publication Year
0,9780930193904,#$@&! : the official Lloyd Llewellyn collection,Official Lloyd Llewellyn collection,"Clowes, Daniel","Clowes, Daniel [person]",England ; United States of America,"London ; Seattle, Washington",Fantagraphics ; Turnaround,1997
1,9780992664220,#WhatDoYouSee? : a graphic novel anthology of ...,NaN,NaN,Fulfilling Lives (Programme) [organisation],England,Newcastle upon Tyne,Roots & Wings,2018
2,9781302903299,#takebacktheshield,NaN,"Spencer, Nick","Spencer, Nick, author [person]",United States of America,New York,Marvel Worldwide,2017
3,9781607065166,'68. Volume 1. Better run through the jungle,Better run through the jungle,"Kidwell, Mark","Fotos, Jay [person] ; Jones, Nat, 1976- [perso...",United States of America,"Berkeley, California",Image Comics,2012
4,9781600107672,'Bots of science,Trans formers ; Trans formers animated : bots ...,"Bryant, Megan E.","Robbins, Robbie [person] ; Boo, 1981- [person]...",United States of America,"San Diego, California",NaN,2010
...,...,...,...,...,...,...,...,...,...
28687,9780805094886,مترو,Metro : a story of Cairo ; Mitrū. English,"Shāfiʿī, Majdī","Rossetti, Chip, translator [person] ; Shāfiʿī,...",United States of America,New York,Henry Holt ; Metropolitan,2012
28688,9781569708354,丘の上の楽園. English,Oka no ue no rakuen. English ; The paradise on...,"Tenzen, Momoko","Tenzen, Momoko [person] ; 天禅桃子 [person]",United States of America,Gardena,Digital Manga Pub,2007
28689,9781891830914,信じられない変更ロボット,Incredible change-bots : more than just machin...,"Brown, Jeffrey","Brown, Jeffrey, 1975- [person]",United States of America,"Marietta, Georgia",Top Shelf Productions,2007
28690,9787222155145,喜欢我也没关系,Xi huan wo ye mei guan xi,"Wang, Chacha","Wang, Chacha, author [person] ; 王, Xx, author ...",China,Kunming Shi,Yunnan ren min chu ban she ; 云南人民出版社,2017
28691,9789810422134,幻猪TKG千禧年之章 : 糕,Huan zhu TKG qian xi nian zhi zhang : Gao,"Tan, Chub","Tan, Chub, 1973- [person] ; 陈啸宇, 1973- [person]",Singapore,Xin jia po,Feng yun chu ban she ; 风云出版社,2000

In [10]:
# Calculate the number of unique authors in the DataFrame
num_authors = len(comic_df['Author'].unique())

# Calculate the number of unique publication countries in the DataFrame
num_countries = len(comic_df['Country of Publication'].unique())

# Print the number of unique authors and countries. 
print(num_authors)
print(num_countries)

4249
62

In [9]:
# Calculate the earliest/latest year a book was published
early_yr = comic_df['Publication Year'].min()
late_yr = comic_df['Publication Year'].max()

# Print the earliest and latest year of publication.
print(early_yr)
print(late_yr)

1941
2021

In [12]:
# Place all of the data found into a summary DataFrame
comic_summ_df = pd.DataFrame([
    {'Total Unique Authors' : num_authors, 'Total Unique Publication Countries' : num_countries, 'Earliest Year' : early_yr, 'Latest Year' : late_yr}
]
)
comic_summ_df

,Total Unique Authors,Total Unique Publication Countries,Earliest Year,Latest Year
0,4249,62,1941,2021